# Generated by Django 4.2.16 on 2025-06-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mess',
            new_name='message',
        ),
    ]
