# Generated by Django 4.2.16 on 2025-06-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byer', '0002_rename_mess_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
