# Generated by Django 4.2.16 on 2025-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byer', '0003_remove_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersgimup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=50)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
