# Generated by Django 4.1.13 on 2025-07-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byer', '0004_usersgimup'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('cod', 'cod'), ('card', 'card'), ('card', 'Credit/Debit Card'), ('upi', 'upi')], max_length=20)),
            ],
        ),
    ]
