# Generated by Django 4.2 on 2025-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mainitem_images/'),
        ),
    ]
