# Generated by Django 4.2.16 on 2025-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_mainitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='des',
            field=models.CharField(default='No description provided', max_length=300),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media_images/'),
        ),
    ]
