# Generated by Django 4.2.16 on 2025-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_mainitem_des_alter_mainitem_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='firut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media_images/')),
                ('des', models.CharField(default='No description provided', max_length=300)),
            ],
        ),
    ]
