# Generated by Django 4.2.16 on 2025-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
