# Generated by Django 4.2.16 on 2025-06-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_signup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('your_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=25)),
                ('main_category', models.CharField(max_length=25)),
                ('item_name', models.CharField(max_length=56)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
