# Generated by Django 4.2.16 on 2025-06-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.DateTimeField(auto_now_add=True)),
                ('farmer_name', models.CharField(max_length=25)),
                ('product', models.CharField(max_length=25)),
                ('quantity', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('packaging', models.CharField(choices=[('Loose', 'Loose'), ('Bagged (25kg) ', 'Bagged (25kg)'), ('Bagged (50kg)', 'Bagged (50kg)'), ('Custom', 'Custom')], max_length=50)),
                ('description', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=50)),
                ('delivery', models.CharField(choices=[('Self Pickup', 'Self Pickup'), ('Courier', 'Courier'), ('Transport', 'Transport')], max_length=50)),
                ('contact', models.CharField(max_length=25)),
            ],
        ),
    ]
