# Generated by Django 4.2.16 on 2025-06-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_sellproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='list',
            new_name='list_at',
        ),
    ]
