# Generated by Django 4.2.16 on 2025-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_rename_list_sellproduct_list_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='delivery',
            field=models.CharField(choices=[('self_pickup', 'Self Pickup'), ('courier', 'Courier'), ('transport', 'Transport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='packaging',
            field=models.CharField(choices=[('Loose', 'Loose'), ('Bagged_25kg', 'Bagged (25kg)'), ('Bagged_50kg', 'Bagged (50kg)'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
