# Generated by Django 4.2.16 on 2025-06-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_sellproduct_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='delivery',
            field=models.CharField(choices=[('self_pickup', 'Self_Pickup'), ('courier', 'Courier'), ('transport', 'Transport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='image',
            field=models.ImageField(upload_to='sellproduct'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='packaging',
            field=models.CharField(choices=[('Loose', 'Loose'), ('Bagged_25kg', 'Bagged_25kg'), ('Bagged_50kg', 'Bagged_25kg'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
