# Generated by Django 4.2.16 on 2025-06-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_sellproduct_delivery_alter_sellproduct_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='quantity',
            new_name='quantity_kg',
        ),
    ]
