# Generated by Django 4.2.16 on 2025-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_remove_sellproduct_price_sellproduct_price_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='price_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
