# Generated by Django 4.2.16 on 2025-06-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_alter_sellproduct_price_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
    ]
